version: "3.9"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: "mssql"
    restart: always
    ports: 
        - 1433:1433
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=145ef22e-1b0e-4c16-8103-d88a6994b127
